apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-057e3731199143ecac80500e418cea8b-depl
  labels:
    app: coll-057e3731199143ecac80500e418cea8b
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-057e3731199143ecac80500e418cea8b
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-057e3731199143ecac80500e418cea8b
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-057e3731199143ecac80500e418cea8b
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-057e3731199143ecac80500e418cea8b
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping